/* GENERATED by tools/sync_events.py from ClickUp on 2026-10-02 16:06. Do not edit by hand,
   the next daily run overwrites it. Edit the event in ClickUp instead. */
window.EVENTS_LIVE = [
  {
    "date": "2026-08-27",
    "title": "ALPFAsado",
    "where": "Vista Del Sol Pool",
    "kind": "Social"
  },
  {
    "date": "2026-08-31",
    "title": "I-Week",
    "where": "",
    "kind": "Social",
    "end": "2026-09-04"
  },
  {
    "date": "2026-09-01",
    "title": "All About ALPFA",
    "where": "",
    "kind": "Professional"
  },
  {
    "date": "2026-09-03",
    "title": "Jeopardy Night",
    "where": "Wilson Hall 105",
    "kind": "Social"
  },
  {
    "date": "2026-09-08",
    "title": "GBM #1 - Freeport McMoRan",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-10",
    "title": "L&L #1 - Ford",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-15",
    "title": "GBM #2 - Intern Panel",
    "where": "",
    "kind": "Professional"
  },
  {
    "date": "2026-09-17",
    "title": "CC #1 - Sherwin Williams",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-17",
    "title": "L&L #2 - LPL Financial",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-17",
    "title": "Pool Party X BRASA",
    "where": "Vista Del Sol",
    "kind": "Social"
  },
  {
    "date": "2026-09-18",
    "title": "Case comp. X HLSAA",
    "where": "",
    "kind": "Professional"
  },
  {
    "date": "2026-09-21",
    "title": "L&L #3 - Bank Of America",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-22",
    "title": "GBM #3 - Dell",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-23",
    "title": "What is ALPFA, Personal Branding and LinkedIn",
    "where": "Memorial Union - MU 224 Gila",
    "kind": "Professional"
  },
  {
    "date": "2026-09-24",
    "title": "Latino Festival",
    "where": "Nelson Fine Arts Plaza",
    "kind": "Social"
  },
  {
    "date": "2026-09-28",
    "title": "L&L #4 - Eide Bailly",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-29",
    "title": "GBM #4 - Gallo",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-30",
    "title": "ALPFA ASU Career Fair",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-09-30",
    "title": "Resume Workshop",
    "where": "Memorial Union - MU 224 Gila",
    "kind": "Professional"
  },
  {
    "date": "2026-10-01",
    "title": "CC #3 - Gallo",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-10-01",
    "title": "E-Board Meeting #1",
    "where": "",
    "kind": "Board"
  },
  {
    "date": "2026-10-06",
    "title": "GBM #5 - LPL Financial",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-10-07",
    "title": "Networking and Career Fair Prep",
    "where": "Memorial Union - MU 224 Gila",
    "kind": "Professional"
  },
  {
    "date": "2026-10-08",
    "title": "BSC Symposium",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-10-14",
    "title": "Al and Excel",
    "where": "Memorial Union - MU 224 Gila",
    "kind": "Professional"
  },
  {
    "date": "2026-10-19",
    "title": "L&L #7 - GuidePoint",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-10-20",
    "title": "GBM #6",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-10-21",
    "title": "Interview Skills and Mock Interviews",
    "where": "Memorial Union - MU 224 Gila",
    "kind": "Professional"
  },
  {
    "date": "2026-10-22",
    "title": "Volleyball Tournament",
    "where": "SDFC Fields",
    "kind": "Social"
  },
  {
    "date": "2026-10-28",
    "title": "Case Announcement",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-11-03",
    "title": "E-Board Meeting #2",
    "where": "",
    "kind": "Board"
  },
  {
    "date": "2026-11-04",
    "title": "Case Competition",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-11-06",
    "title": "Ice Skating Social",
    "where": "Mullett Arena",
    "kind": "Social"
  },
  {
    "date": "2026-11-10",
    "title": "GBM #7",
    "where": "",
    "kind": "Networking"
  },
  {
    "date": "2026-11-12",
    "title": "ISSC Tabling Event",
    "where": "",
    "kind": "Social"
  },
  {
    "date": "2026-11-18",
    "title": "Final Mentorship Project",
    "where": "",
    "kind": "Professional"
  },
  {
    "date": "2026-11-24",
    "title": "Eboard Meeting #3",
    "where": "",
    "kind": "Board"
  },
  {
    "date": "2027-03-01",
    "title": "Suns Game and Panel",
    "where": "",
    "kind": "Social"
  }
];
