/* ARCHIVED 2026-10-06. This was the fourth tab on opportunities.html, "Pipelines",
   57 multi-year programmes in 8 groups, every link verified when it was built.
   Renars replaced the tab with Certificates. The data is kept here, not served,
   so it can come back: paste the const into data.js above ALUMNI and restore
   the `pipelines` entry in VIEWS in opportunities.html (see git history for
   commit "Replace the Pipelines tab with Certificates"). */

/* ------------------------------------------------------------
   PIPELINES
   The third thing, and the most misunderstood. Not a scholarship and not
   an internship: the multi year programme that GETS you the internship.
   Management Leadership for Tomorrow is the archetype.

   Most of these target SOPHOMORES, which is the opposite of the
   internship board, so targetYear is the field that matters most.

   Several were restructured after 2023 legal pressure on race conscious
   eligibility. What is recorded here is what each page says TODAY, not
   what the programme was historically known for. Do not describe one as
   Latino specific unless its current page does.
------------------------------------------------------------ */
const PIPELINES = [
  {
    key: "diversity", name: "Latino and diversity pipelines",
    blurb: "Multi-year programmes that coach you, put you in front of employers and get you the internship, most of them starting in your sophomore year.",
    items: [
      {
        name: "Career Prep", provider: "Management Leadership for Tomorrow (MLT)",
        targetYear: "Sophomore",
        whatYouGet: "Roughly 20 months of structured programming from sophomore year through senior year: a personal MLT coach, a written career roadmap, resume and interview work, national seminars hosted on corporate partner campuses, and direct access to partner employers recruiting for internships and full-time roles. MLT says 90 percent of Career Prep Fellows have a full-time offer before graduation.",
        eligibility: "College sophomore graduating Fall 2028, Spring 2029 or Summer 2029. Bachelor's degree at a four-year accredited school. No minimum GPA stated, but competitive applicants have at least a 3.0 cumulative. All majors accepted, career interest in business or technology. You must show lived experience with inequitable access to career accelerating resources, and commit to monthly assignments and every required seminar.",
        citizenship: "U.S. citizen or U.S. permanent resident. The eligibility page names DACA participants as included.",
        openToBusiness: "",
        cycle: "Applications for the sophomore class opened for 2026-27. Priority track deadlines: Finance August 1 2026, Consulting September 1 2026, Software Engineering / Technology / Corporate Management November 1 2026. General deadline December 1 2026, final deadline January 15 2027. Apply by the priority deadline and you are guaranteed a spot in that track's bootcamp.",
        link: "https://mlt.org/career-prep/",
        note: "The track deadlines are the real deadline. If you want finance you had to be in by August 1, so treat the summer before sophomore year as the moment to apply, not the spring. The page also says MLT programmes are open to all who meet the criteria regardless of race, ethnicity or gender, so being Latino is not itself the qualifier, the access gap is.",
      },
      {
        name: "SEO Career", provider: "Sponsors for Educational Opportunity (SEO USA)",
        targetYear: "Freshman",
        whatYouGet: "Two phases. Phase 1 Edge gives you career prep, industry training, coaching and personalised resume and interview feedback plus access to internship openings. Phase 2 Success is the internship placement itself, with a mandatory Career Summit in New York before the summer starts. SEO says more than 80 percent of its summer internships lead to full-time offers.",
        eligibility: "First year, sophomore or junior at an accredited four-year U.S. university. 3.2 GPA required, 3.0 may be considered. All majors. First-year students can apply with no GPA to register interest, then update it. You must complete industry training, coaching sessions, interview prep and required events.",
        citizenship: "Must be work authorised in the U.S. The page adds that F-1 students may be eligible for Phase 2: Success. DACA is not mentioned either way.",
        openToBusiness: "",
        cycle: "Rolling, year-round. Edge applications are reviewed continuously. Candidates seeking summer internships with partners are reviewed October through April, and the Success class typically closes in mid-April. Expect 6 to 8 weeks for a response.",
        link: "https://career.seo-usa.org/apply-faq/",
        note: "Getting into Edge does not guarantee an internship and does not automatically move you to Success, which is a separate invitation. Apply as a freshman anyway, because Edge is the free coaching and you lose nothing by being in it early.",
      },
      {
        name: "INROADS Internship Program", provider: "INROADS",
        targetYear: "Any",
        whatYouGet: "A shot at a paid multi-year internship with one of 200-plus employer partners, preceded by a six-week cohort training, an interview guidance and preparation session, and year-round coaching from an assigned INROADS advisor. You attend the mandatory INROADS National Conference. Many participants return to the same employer across multiple summers and convert to full-time.",
        eligibility: "Full-time undergraduate at an accredited college with at least one summer left before graduation. Cumulative GPA 3.0 or higher. Majors in business, STEM or liberal arts. Application needs an INROADS-formatted resume and an unofficial transcript.",
        citizenship: "The programme page states no citizenship rule. The placements are paid U.S. roles, so employer work authorisation applies. Confirm with INROADS directly rather than assuming.",
        openToBusiness: "",
        cycle: "Applications are open on the site now for the following summer. INROADS does not publish a single hard deadline on the programme page, so apply in the autumn.",
        link: "https://inroads.org/internships-program/",
        note: "INROADS says outright that internships are not guaranteed, even after you are accepted and trained. The interview with corporate partners is a real gate. Also note the resume template is mandatory, a normal resume gets rejected on format.",
      },
      {
        name: "ALPFA Fellowship Program", provider: "ALPFA National",
        targetYear: "Any",
        whatYouGet: "Real-world business case work in small pods, professional development sessions and corporate mentorship, with the fellowship culminating at the ALPFA Convention. It is the national programme your own chapter membership unlocks.",
        eligibility: "Open to college students. The page states it is for Premium members only, so you need a paid ALPFA student membership, not just chapter involvement. You do not need an ALPFA chapter at your school, but ASU has one.",
        citizenship: "Not stated on the page.",
        openToBusiness: "",
        cycle: "Applications are currently CLOSED. Every date on the page, applications open, applications due, winners notified, fellowship begins, reads TBD as of September 2026. Put your email on the notify list rather than waiting to check.",
        link: "https://www.alpfa.org/fellowship",
        note: "This is the one on the list you have the most leverage over, because you are already inside ALPFA. The blocker is the Premium membership tier, which is worth checking with your chapter before the cycle opens so nobody misses it on a paperwork technicality.",
      },
      {
        name: "ALPFA Convention", provider: "ALPFA National",
        targetYear: "Any",
        whatYouGet: "A multi-day national gathering that functions as a hiring event. The 2025 convention drew 6,342 registered attendees, 33 percent of them students, with 85 companies at the career fair across 39 industries and 1,798 interviews scheduled on site. ALPFA also distributed 1.2 million dollars in scholarships at the 2025 event.",
        eligibility: "Open to students, professionals and corporate partners. Registration required. Discounted student tickets are advertised.",
        citizenship: "Not stated. It is an event, not a placement programme.",
        openToBusiness: "",
        cycle: "ALPFA Convention 2026 is August 9 to 13, 2026 in Charlotte, North Carolina. Registration is open on the page.",
        link: "https://www.alpfa.org/event-convention",
        note: "1,798 interviews for roughly 3,000 students is the number that matters. You go with a resume and interview slots already booked, not to browse. Book travel and the chapter's block early, because the discounted student rate and the interview scheduling both close well before the event.",
      },
      {
        name: "TLF Undergraduate Scholarship and Career Development Program", provider: "The LAGRANT Foundation",
        targetYear: "Sophomore",
        whatYouGet: "A 2,500 dollar award plus a paid trip to Washington D.C. for a welcome dinner, three days of career development workshops and a donor reception, and a mandatory one-year commitment to stay in contact with the foundation for professional guidance and academic support. The mentorship, not the money, is the pipeline part.",
        eligibility: "Current freshman, sophomore, junior or non-graduating senior. Priority goes to rising juniors and seniors. Full-time at a four-year accredited U.S. institution, 12 or more units. Minimum 3.0 GPA, with an optional essay if your GPA does not reflect your ability. You must major in a field with an emphasis in advertising, marketing or public relations, and have at least one year left after the April award.",
        citizenship: "U.S. citizen, permanent resident or DACA recipient. Stated explicitly.",
        openToBusiness: "",
        cycle: "2027 cycle: applications due 5:00 p.m. PST February 15, 2027. Submit by 11:59 p.m. PST January 18, 2027 for 10 bonus points on your application. Scholarship activities in Washington D.C. run April 25 to 28, 2027.",
        link: "https://lagrantfoundation.org/scholarship-application-process/",
        note: "Only useful if you are on the marketing or communications side of business, it will not take a straight accounting or finance major. The 10-point early bonus is a free edge that most applicants ignore, and attendance in D.C. is not optional, skip it and you forfeit the award.",
      },
      {
        name: "Congressional Internship Program", provider: "Congressional Hispanic Caucus Institute (CHCI)",
        targetYear: "Any",
        whatYouGet: "A paid placement in a congressional office in Washington D.C., 4,776 dollars for the summer session or 5,400 dollars for the fall, plus furnished housing with rent and utilities covered, round-trip domestic travel, medical insurance with premiums paid, a 100 dollar monthly Metro stipend, an 8-day orientation and weekly leadership development sessions.",
        eligibility: "Enrolled full time working toward an undergraduate degree in the academic period before the programme. Recent graduates from the term immediately prior may apply. Preference for 3.0 GPA or higher. Community college students graduating in June are eligible for summer if they are transferring to a four-year school in the fall. Application needs a one-page resume, an unofficial transcript, one professional recommendation and three essays of 300 to 600 words.",
        citizenship: "U.S. citizens, lawful permanent residents, asylees, or anyone lawfully authorised to work full time without restriction with valid evidence of employment authorisation. International students on F-1 or M-1 visas are NOT eligible. DACA recipients must hold valid work authorisation at acceptance and keep it for the whole programme.",
        openToBusiness: "",
        cycle: "Applications launched August 15, 2026. Summer 2027 deadline December 1, 2026, programme runs May 19 to July 30, 2027. Fall 2027 deadline March 1, 2027, programme runs August 18 to November 12, 2027.",
        link: "https://chci.org/programs/congressional-internship-program/",
        note: "CHCI says explicitly it wants finance, economics and accounting backgrounds, not just political science. A business major is an asset here, not a mismatch. Apply to every session you are eligible for, the pools are small and the selection committee is the same people.",
      },
    ],
  },
  {
    key: "finance", name: "Bank and finance sophomore programmes",
    blurb: "Early insight and fellowship programmes that banks run a full year before internship recruiting, so the people in them are already interviewing while everyone else is writing a first resume.",
    items: [
      {
        name: "JPMorganChase Fellowship Program", provider: "JPMorganChase, with the Office of Black Affairs and the Office of Hispanic and Latino Affairs",
        targetYear: "Sophomore",
        whatYouGet: "A five-week PAID, full-time summer fellowship in a selected JPMorganChase office. A project-based curriculum on financial services, teamwork and problem solving, plus leadership and technical training. The firm describes it as building a pathway to future employment, which in practice means the summer analyst internship the following year.",
        eligibility: "Sophomore students. The page says the programme is seeking sophomores including, without limitation, Black, Hispanic and Latino students, and then states that all sophomore students interested in the programme, regardless of background, are welcome to apply. Tracks have historically included Banking and Markets, Corporate Strategy and General Management, and Software Engineering.",
        citizenship: "Not stated on the programme page. It is a paid U.S. role, so employer work authorisation applies.",
        openToBusiness: "",
        cycle: "Applications open in the autumn for the following summer and appear by location, so the Apply Now panel only shows locations currently open. The 2026 cycle opened in November 2025. Follow the Talent Network to be told when 2027 opens.",
        link: "https://www.jpmorganchase.com/careers/explore-opportunities/programs/jpmcfellowship",
        note: "This is the consolidation of what JPMorgan used to run as separate named programmes including Sophomore Edge, Advancing Black Pathways and Winning Women. The eligibility wording was rewritten after 2023 to be open to all sophomores, so do not assume you are excluded, and do not expect the old programme names to still work as search terms.",
      },
      {
        name: "Early Identification (Early ID) Program", provider: "Citi",
        targetYear: "Sophomore",
        whatYouGet: "A virtual mentorship programme with technical training, interview preparation specifically for Summer Analyst roles, and what Citi calls a direct pathway to future opportunities. You apply to a maximum of two lines of business.",
        eligibility: "U.S. sophomores enrolled in a four-year bachelor's degree.",
        citizenship: "Not stated. Citi runs the programme for U.S. sophomores.",
        openToBusiness: "",
        cycle: "Two intakes a year. A March start with applications opening in February, and a December start with applications opening in November. That is the only listed cycle on Citi's pre-internship page.",
        link: "https://jobs.citi.com/early-career-programs-pre-internships",
        note: "Two intakes means two shots in the same sophomore year. Take the November one, because it lands before summer analyst recruiting rather than during it. Everything at Citi, programmes and event registrations alike, goes through Workday and shows up labelled as a job, which confuses people into thinking they applied to the wrong thing.",
      },
      {
        name: "Freshman Discovery", provider: "Citi",
        targetYear: "Freshman",
        whatYouGet: "An introductory programme with training, workshops, foundational technical skills and industry insight. It is the entry rung below Early ID.",
        eligibility: "All first-year students in a four-year bachelor's degree at an accredited U.S. institution, regardless of major. Citi says students with limited prior exposure to financial services are particularly encouraged.",
        citizenship: "Not stated.",
        openToBusiness: "",
        cycle: "Starts in May, with applications opening in late March or early April.",
        link: "https://jobs.citi.com/early-career-programs-pre-internships",
        note: "The line about limited prior exposure is not filler. This is the one programme on this whole list where knowing nothing yet is an advantage rather than a disqualifier, so a first-year with no finance background should apply rather than wait a year.",
      },
      {
        name: "Student Leaders", provider: "Bank of America",
        targetYear: "Freshman",
        whatYouGet: "A paid six-week full-time summer internship at a local nonprofit at 17 dollars an hour or local minimum wage, whichever is higher, plus a three-day national Leadership Summit with all travel, hotel and meals paid by the bank. Roughly 300 students a year.",
        eligibility: "READ THIS CAREFULLY, IT CHANGED. You must be at least 18, have earned your high school diploma within the last 24 months, and have earned at least 12 and no more than 18 credit hours of post-secondary credit. That makes it a programme for students in their first year of college, not for high school students. You also need two recommendations, a transcript, a leadership role within the last 24 months, and you must live in an eligible programme location for the summer. You are ineligible if you were previously selected as a high school student.",
        citizenship: "Must be legally authorised to work in the United States without sponsorship through the end of the programme summer. Stated explicitly.",
        openToBusiness: "",
        cycle: "The published 2026 cycle opened February 9, 2026 and closed March 16, 2026 at 11:59 pm Eastern with no extensions. Applicants were notified by the end of April, the Leadership Summit ran June 16 to 18, 2026 and the internship started mid-June. The page still shows that 2026 cycle, so treat February as the opening month for 2027 and confirm.",
        link: "https://about.bankofamerica.com/en/making-an-impact/student-leaders",
        note: "Most people, including most advisers, still think Student Leaders is a high school programme. The current eligibility, 12 to 18 post-secondary credit hours, means a college first-year applying in the spring of freshman year is exactly the target. You intern at the nonprofit, not at Bank of America, and living expenses during the internship are on you.",
      },
      {
        name: "Possibilities Series", provider: "Goldman Sachs",
        targetYear: "Freshman",
        whatYouGet: "An introduction to financial services for first-year students, built around interactive skills workshops and network building with Goldman people. It is the firm's earliest touchpoint in the Americas.",
        eligibility: "First-year undergraduates graduating between December 2028 and May 2029 attending a U.S. college or university. Location confirmed on acceptance.",
        citizenship: "Not stated on the programme page.",
        openToBusiness: "",
        cycle: "The page currently reads Applications are now closed and lists programme dates of Spring 2026, so it is showing a PAST cycle as of September 2026. The equivalent next cycle would target first-years graduating a year later. Watch the programmes and internships listing for the reopen.",
        link: "https://www.goldmansachs.com/careers/students/programs-and-internships/americas/possibilities-series",
        note: "Goldman's programme listing is a JavaScript filter, so browsing it turns up nothing useful and the individual pages are the only real content. Bookmark the Americas programmes and internships page and re-check it each autumn rather than trying to search for programme names.",
      },
      {
        name: "Early Insights", provider: "Morgan Stanley",
        targetYear: "Sophomore",
        whatYouGet: "Workshops, networking with Morgan Stanley staff, and participation in the first stage of Summer Analyst recruiting. The value is the accelerated interview access, not the content.",
        eligibility: "COULD NOT CONFIRM FROM THE FIRM'S OWN PAGE. Morgan Stanley has retired its standalone programme pages, and every old Early Insights URL now redirects to the general Career Opportunities Search filtered to Students and Graduates. Treat the second-year eligibility described on third-party sites as unverified until you see a live posting.",
        citizenship: "Not stated anywhere we could verify on a Morgan Stanley page.",
        openToBusiness: "",
        cycle: "Not published on a firm page. Postings appear on the career search, historically in the autumn for the following spring and summer.",
        link: "https://www.morganstanley.com/careers/career-opportunities-search?opportunity=sg",
        note: "The reason you cannot find a Morgan Stanley Early Insights page is that there is not one any more, not that you are searching badly. Set an alert on the career search rather than hunting for a programme landing page, and verify the year requirement on the actual posting.",
      },
    ],
  },
  {
    key: "consulting", name: "Consulting and accounting sophomore programmes",
    blurb: "Consulting firms recruit a year earlier than anyone else, so the sophomore programmes here are how you get into a junior-year summer associate seat.",
    items: [
      {
        name: "Growing Future Leaders (GFL)", provider: "Boston Consulting Group",
        targetYear: "Sophomore",
        whatYouGet: "A paid summer internship in a BCG U.S. or Canadian office during your sophomore summer, working on a real case team with an assigned mentor and formal training. Complete it successfully and you are eligible for a scholarship plus an offer to return as a Summer Associate after your junior year, which is the seat everyone else spends junior year competing for.",
        eligibility: "Current sophomore at a U.S. or Canadian university. BCG's programme page is a JavaScript job-board template and the eligibility panel would not load for us, so treat the graduation window and any background criteria as UNCONFIRMED until you read the live posting. Historically the programme also carried race and ethnicity criteria, which is exactly the kind of wording that has been rewritten across the industry since 2023, so read the current posting rather than any summary of it, this one included.",
        citizenship: "Not confirmed.",
        openToBusiness: "",
        cycle: "Applications have historically opened in late summer for the following summer, so autumn of sophomore year is the window. Confirm on the page.",
        link: "https://careers.bcg.com/global/en/on-campus/programs/growing-future-leaders",
        note: "This is the single highest-leverage item on this list for anyone who wants consulting, because it collapses two recruiting cycles into one. It is also the item whose published eligibility we could least verify, so read the posting itself and do not rely on what a forum or a prep site says it used to require.",
      },
      {
        name: "First Forward", provider: "Bain & Company",
        targetYear: "Sophomore",
        whatYouGet: "A 1.5 day in-person summit with case discussions and simulations, professional development workshops, networking with Bain consultants, resume and personal brand coaching, and access to Bain's First-Generation Low-Income affinity group.",
        eligibility: "Quoted from Bain: sophomore/second-year students attending a school in the U.S. or Canada with an anticipated graduation date between December 2027 and Summer 2028. Bain adds that it is for students who are the first in their family to go to college or who identify with growing up in a lower socio-economic household.",
        citizenship: "No citizenship requirement mentioned.",
        openToBusiness: "",
        cycle: "Applications are CLOSED as of September 2026. The page says to check back for the next cycle and gives no dates.",
        link: "https://www.bain.com/careers/work-with-us/internships-programs/first-forward/",
        note: "First-generation or low-income is the actual qualifier here, not ethnicity. If you are the first in your family at university, say so plainly in the application, because it is the criterion being screened for rather than something to downplay.",
      },
      {
        name: "Consulting Kickstart", provider: "Bain & Company",
        targetYear: "Sophomore",
        whatYouGet: "A virtual three-part webinar series in October covering what consulting actually is, direct contact with Bain recruiters and recent hires, an explanation of the recruiting process, and guidance on choosing an office preference. It is low commitment and fits around classes.",
        eligibility: "Second-year (sophomore) undergraduates attending a four-year university in the United States or Canada.",
        citizenship: "Not stated.",
        openToBusiness: "",
        cycle: "Applications are OPEN, deadline Monday October 5 at 11:59 pm PST, with the series running in October.",
        link: "https://www.bain.com/careers/work-with-us/internships-programs/consulting-kickstart/",
        note: "This is the easiest thing on the entire list to get into and the deadline is weeks away. It is three webinars, not an internship, so the value is that Bain recruiters now know your name before junior-year recruiting starts. Do this one first.",
      },
      {
        name: "Discovery Internship", provider: "Deloitte",
        targetYear: "Sophomore",
        whatYouGet: "A paid summer internship for first-year and sophomore students, placed on one or more real client projects with an assigned mentor, plus national and local learning and networking events. Length varies by service line, so read the posting. Strong performers are routed toward the full junior-year internship.",
        eligibility: "Postings are titled Discovery Intern (Freshman/Sophomore) or Discovery Intern (Sophomore/Junior) and are split by service line, Audit and Assurance, Tax, Risk and Financial Advisory, and Deloitte Technology, and by profile, Accounting or Business/Technology. Accounting-profile postings require definitive plans to pursue a bachelor's in accounting or a related field AND CPA eligibility, meaning the credit hours to sit for the CPA exam on graduation. Check the graduation-year requirement on each posting, it is specific and it changes every cycle.",
        citizenship: "Not stated in the general description. Check the individual posting.",
        openToBusiness: "",
        cycle: "Rolling, and it runs early. Postings for a given summer appear around September of the preceding year and recruiting for that summer closes around May 1. Deloitte fills seats as strong applicants appear, so applying in September beats applying in January.",
        link: "https://apply.deloitte.com/en_US/careers/SearchJobs?keyword=Discovery",
        note: "There is no single Discovery landing page to bookmark, only job postings, which is why students never find it. Search the term Discovery on Deloitte's job site and filter by service line. The CPA-eligibility clause on accounting postings is a hard gate, so if you are on a 120-hour track, check your credit plan before you apply.",
      },
      {
        name: "Advance", provider: "PwC",
        targetYear: "Junior",
        whatYouGet: "PwC's internship experience: real client work alongside PwC staff, technical and digital skills training, coaching and feedback, and a professional network inside the firm. It is the internship itself rather than a pre-internship programme.",
        eligibility: "Undergraduates heading into the internship year. PwC does not publish a separate sophomore pre-internship programme page today.",
        citizenship: "PwC states plainly that it is not hiring experienced or entry-level candidates who will need PwC sponsorship through the H-1B lottery now or in the future, with a narrow exception: only the Chinese, Japanese and Korean Business Network roles are eligible for sponsorship and for the Destination CPA Program.",
        openToBusiness: "",
        cycle: "Follows PwC's entry-level recruiting calendar. Postings are on the PwC entry-level job search.",
        link: "https://jobs-us.pwc.com/us/en/advance",
        note: "Included as a correction, not a recommendation. PwC's named sophomore programmes are no longer on its site, so if someone tells you to apply to PwC Start or PwC Challenge, those pages do not exist any more. The H-1B line is the most concrete citizenship statement of any firm on this list, and international students should read it before spending time on PwC.",
      },
    ],
  },
  {
    key: "tech", name: "Tech pipelines and early-insight programmes",
    blurb: "Mostly technical, but listed here because ASU business students in CIS, business data analytics or information systems qualify for several of them and rarely realise it.",
    items: [
      {
        name: "Explore Microsoft", provider: "Microsoft",
        targetYear: "Sophomore",
        whatYouGet: "A 12-week paid summer internship in the U.S. built specifically for students in their first two years of college. You rotate through the three main phases of the product development cycle, Design, Build and Quality, working in a pod with other Explore interns, with mentoring, community building and networking alongside the work.",
        eligibility: "First or second year full-time enrolled bachelor's student during the academic term immediately before the internship. You need an interest in majoring in a technical discipline: Microsoft names Computer Science, Computer Engineering, Information Technology, Data Science, Electrical Engineering and Cybersecurity. You cannot take classes while interning, and you must be at least 16.",
        citizenship: "Not stated on the programme overview. Check the individual posting on the Microsoft jobs site.",
        openToBusiness: "",
        cycle: "Postings go up on the Microsoft student jobs site and are filled on a rolling basis. Watch from early autumn.",
        link: "https://careers.microsoft.com/v2/global/en/exploremicrosoft",
        note: "Explore is the rare sophomore programme that is a genuine paid engineering internship rather than a networking event, and it is the reason people who did it have a Microsoft line on the resume before junior year. An ASU Computer Information Systems or Business Data Analytics major fits the named disciplines, a straight accounting or finance major does not.",
      },
      {
        name: "ColorStack membership", provider: "ColorStack",
        targetYear: "Any",
        whatYouGet: "Free membership in a national community of Black and Latinx computing students. A Slack workspace for homework help and career advice, monthly workshops and coaching from industry people, a resume drop straight to partner companies, hundreds of posted opportunities a month, and the annual Stacked Up Summit career fair.",
        eligibility: "Black and Latinx Computer Science students. ColorStack states its mission as increasing the number of Black and Latinx Computer Science graduates who go on to technical careers.",
        citizenship: "Not stated.",
        openToBusiness: "",
        cycle: "Membership applications are open on the site. The Stacked Up Summit is annual and currently open for registration.",
        link: "https://www.colorstack.org/",
        note: "The resume drop to partner companies is the part that actually moves the needle, and it costs nothing. This is unambiguously a computing programme, not a business one, so send it to your CIS and data analytics members rather than the whole chapter.",
      },
      {
        name: "CodePath courses and career services", provider: "CodePath",
        targetYear: "Any",
        whatYouGet: "Free applied engineering courses taught by working software engineers, run through your university, plus a separate career services track for students already in the programme. It is skills first, network second, which is the opposite shape of most things on this list.",
        eligibility: "Open through an application portal. Courses are aimed at students building toward software engineering roles. Check the individual course page for prerequisites.",
        citizenship: "Not stated.",
        openToBusiness: "",
        cycle: "Courses run on a semester calendar with an application portal that opens ahead of each term.",
        link: "https://www.codepath.org/courses",
        note: "Worth listing only because it is free and it is the one thing here that fixes an actual skills gap rather than an access gap. If a member keeps failing technical screens, this is the referral, not another networking programme.",
      },
    ],
  },
  {
    key: "consulting2", name: "Consulting pipelines",
    blurb: "Sophomore and freshman early-insight programmes at Bain, BCG and Accenture that lead to the junior-year internship rather than being one.",
    items: [
      {
        name: "Consulting Kickstart", provider: "Bain & Company",
        targetYear: "Sophomore",
        whatYouGet: "A three-part virtual webinar series held in October. You hear from Bain consultants, get recruiters walking you through how Bain actually screens and interviews, and build a named relationship with the recruiting team before junior-year applications open. No stipend, no interview, no offer is promised on the page.",
        eligibility: "Page states: second-year (sophomore) undergraduate students attending a four-year university in the United States or Canada. No major, GPA, background or first-generation criteria stated. Not race-conscious.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "Open right now. Page states applications are open and the deadline is Monday, October 5 at 11:59pm PST. October 5 falls on a Monday in 2026, so this is the current live cycle, not a stale page. Program runs in October.",
        link: "https://www.bain.com/careers/work-with-us/internships-programs/consulting-kickstart/",
        note: "This is the only Bain sophomore programme with a live application as of mid-September 2026. Every other Bain early-insight programme on this list closed months ago and reopens in the spring. If a sophomore does exactly one thing this month, this is it, because it is low-effort, virtual, and it puts you in Bain's system before the BEL and First Forward applications open in the new year.",
      },
      {
        name: "First Forward", provider: "Bain & Company",
        targetYear: "Sophomore",
        whatYouGet: "A 1.5-day in-person summit at a Bain office. Immersive sessions, real case discussions, professional development workshops, resume and personal branding work, and networking with Bain professionals. Hosted in Boston, Chicago, Denver, New York, San Francisco, and Washington DC. The page does not promise a stipend, travel cover, an interview, or an offer.",
        eligibility: "Page states: second-year undergraduates at U.S. or Canadian schools with an anticipated graduation date between December 2027 and Summer 2028, who are first in their families to attend college or who identify with the experience of growing up in a lower socio-economic household. No prior business experience required. This is a first-generation and socio-economic criterion, not a race criterion.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "Closed. Page states applications are closed and to check back for the next cycle. The in-person dates shown are May 28 and 29. Expect the next application window in winter or early spring for a late-May program.",
        link: "https://www.bain.com/careers/work-with-us/internships-programs/first-forward/",
        note: "This is the Bain programme most ALPFA members will actually qualify for, and it is quietly the better-odds door than BEL, because the first-generation and lower-income criterion is self-identified and far fewer students know the programme exists. Bain covers the graduation window explicitly, so a current sophomore graduating in 2028 is exactly in scope for the next cycle.",
      },
      {
        name: "Building Entrepreneurial Leaders (BEL)", provider: "Bain & Company",
        targetYear: "Sophomore. The current page says only \"undergraduate students\" and does not name a class year, but Bain lists BEL alongside its other sophomore exploratory programmes and it has historically been a sophomore programme.",
        whatYouGet: "Exposure to life as a consultant through interactive sessions and conversations with Bain employees, run across 14 or more U.S. and Toronto offices. The current page does not state a stipend, travel cover, guaranteed interview, or offer. Founded in 2009.",
        eligibility: "As written today: undergraduate students. The page states no race, ethnicity, or background criteria. Do not treat this as a Latino-specific or diversity-specific programme based on the current page, whatever older guides say.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "Closed. Page states: applications for the 2026 program are closed, check back later for the 2027 BEL program. The 2026 cycle closed in early February, so expect a January application window.",
        link: "https://www.bain.com/careers/work-with-us/internships-programs/building-entrepreneurial-leaders/",
        note: "The eligibility language on this page was stripped back after 2024. Third-party consulting-prep sites still describe BEL as restricted to Black, Hispanic, and Indigenous sophomores and still quote a stipend and a shot at an Associate Consultant internship offer. Bain's own page now says none of that. Apply on what the page says, and ask the recruiter directly what the outcome is rather than trusting the blogs.",
      },
      {
        name: "Connecting and Resourcing Empowered Women (CREW)", provider: "Bain & Company",
        targetYear: "Sophomore",
        whatYouGet: "Sessions with senior women in strategy consulting on how they built careers at Bain, plus exploration of consulting career paths and leadership development. The page does not state a stipend, an interview, or an offer.",
        eligibility: "Page states: second-year (sophomore) undergraduate students interested in hearing from women leaders in strategy consulting. No stated restriction on who may apply.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "Closed. Page states applications for the 2026 program are closed, check back later for 2027 CREW.",
        link: "https://www.bain.com/careers/work-with-us/internships-programs/crew/",
        note: "Bain runs four separate sophomore doors (Kickstart, CREW, First Forward, BEL) and they are not mutually exclusive. Students routinely pick one and stop. The recruiting team sees the same applicant pool across all four, so showing up in two of them is a cheap way to be a known name rather than a resume.",
      },
      {
        name: "BCG Launch", provider: "Boston Consulting Group",
        targetYear: "Any undergraduate, plus non-MBA master's students. It is the entry point that feeds BCG Embark, which is aimed at students graduating December 2027 to July 2028, so sophomores are the core audience.",
        whatYouGet: "A virtual session series covering consulting fundamentals, the BCG Associate application process, and life at BCG. All content is available on demand and recordings are posted to the portal. One registration gets you every session. The page states plainly that signing up is not a job application.",
        eligibility: "Page states: undergraduate and non-MBA master's students from all fields and backgrounds attending a college or university in the U.S. or Canada. Open to everyone.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "Registration is currently closed. Page states registration opens six weeks before sessions kick off, and that the portal closes May 29, 2026. That May date refers to the cycle that has already run, so the page is showing a past cycle.",
        link: "https://careers.bcg.com/global/en/on-campus/programs/bcg-launch",
        note: "Register for Launch even if you only care about Embark. Embark has no separate application at all: BCG selects Embark participants out of the Launch registrant pool based on a checkbox you tick during Launch registration. Miss Launch and you cannot reach Embark.",
      },
      {
        name: "BCG Embark", provider: "Boston Consulting Group",
        targetYear: "Sophomore. Page states current undergraduates in a U.S. program with an anticipated graduation date between December 2027 and July 2028.",
        whatYouGet: "A virtual conference with panels, case interview preparation, and direct connection to BCG consultants in the Black@BCG, Latin@BCG, and Indigenous@BCG networks. No stipend, interview, or offer is stated.",
        eligibility: "Hosted in partnership with the Black@BCG, Latin@BCG, and Indigenous@BCG networks, and aimed at students who have demonstrated leadership and a commitment to fostering community and belonging. The FAQ states explicitly: \"BCG Embark is open to candidates of all backgrounds.\" The affinity networks themselves are described as open to all BCGers. So it is affinity-network-aligned but not identity-restricted.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page. U.S. offices only.",
        openToBusiness: "",
        cycle: "Past cycle shown. Page states register via the BCG Launch form by April 15, 2026 for a virtual conference on May 14, 2026. Both dates have passed. Expect the same rhythm in spring 2027.",
        link: "https://careers.bcg.com/global/en/on-campus/programs/embark",
        note: "This is the closest thing on the whole list to a Latino-facing programme at a top consulting firm, and it is nearly invisible because it has no application of its own. The mechanism is: register for BCG Launch, then tick interest in Latin@BCG. If you already registered for Launch without ticking it, BCG's page says to email associate.recruiting@bcg.com and name the network.",
      },
      {
        name: "BCG Advance", provider: "Boston Consulting Group",
        targetYear: "Junior. It was moved off sophomores this cycle.",
        whatYouGet: "A half-day invite-only virtual conference with panels and skill-building sessions on navigating the recruiting process. The page states directly that attending does NOT include an interview for a summer internship, and that the full-time application must be submitted separately.",
        eligibility: "Page states: current juniors or third-year students at a college or university in the U.S. or Canada, graduating between December 2026 and July 2027, interested in the Women@BCG network, which is described as open to all. Open to all fields of study and backgrounds.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page. U.S. and Canada offices only; selecting an office elsewhere disqualifies your submission.",
        openToBusiness: "",
        cycle: "Past cycle shown. Page states register by April 24, 2026 for a Zoom conference on May 21, 2026. Both dates have passed.",
        link: "https://careers.bcg.com/global/en/on-campus/programs/bcg-advance",
        note: "BCG moved Advance from sophomores to juniors this year and says so in its own FAQ, promising instead \"expanded opportunities\" for sophomores. In practice that expanded opportunity is Launch and Embark, which are lighter-touch. If you are a sophomore who found Advance on an old guide, you are one year early and should go to Launch instead.",
      },
      {
        name: "Elevate to Innovate Externship", provider: "Accenture",
        targetYear: "Freshman. Accenture states: first-year students enrolled in a four-year undergraduate program at a college or university in the US or Canada.",
        whatYouGet: "A virtual two-day professional development and learning experience with learning sessions, networking, and engagement activities. Accenture states you develop foundational business skills and industry acumen, expand your network, and get a fuller understanding of Accenture's entry-level career opportunities. No stipend, interview, or offer stated.",
        eligibility: "First-year undergraduates in the US or Canada. No race, ethnicity, first-generation, or major criteria stated. Open to all.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "No dates published on the student programmes page. Accenture routes applications through its Workday careers site.",
        link: "https://www.accenture.com/us-en/careers/life-at-accenture/internships-students",
        note: "This is one of very few programmes anywhere aimed at genuine first-years, which makes it the best first thing an ALPFA freshman can put on a resume. Accenture's ladder is unusually explicit: Elevate to Innovate in year one, Innovation Challenge or Student Leadership Program in year two, Summer Analyst in year three. Most firms leave that progression implicit; Accenture prints it, so you can plan three years at once.",
      },
      {
        name: "Accenture Innovation Challenge", provider: "Accenture",
        targetYear: "Sophomore. Accenture states: second-year students enrolled in a four-year undergraduate program at a college or university in the US or Canada.",
        whatYouGet: "Accenture's flagship case competition. Accenture partners with a non-profit, builds a real case around a pressing issue, and student teams compete to present solutions. You develop core consulting skills through the case and see what a career at Accenture looks like. No stipend, interview, or offer stated.",
        eligibility: "Second-year undergraduates in the US or Canada. No race, ethnicity, first-generation, or major criteria stated. Open to all.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "No dates published on the student programmes page.",
        link: "https://www.accenture.com/us-en/careers/life-at-accenture/internships-students",
        note: "A case competition is the one format on this list that produces something you can talk about in an interview at any firm, not just the host. An ALPFA chapter can enter a team together, which turns an individual application into a group activity and solves the hardest part, which is getting people to actually start.",
      },
      {
        name: "Student Leadership Program", provider: "Accenture",
        targetYear: "Sophomore. Accenture states: second-year students enrolled in a four-year undergraduate program at a college or university in the US or Canada.",
        whatYouGet: "A semester-long leadership and professional development programme built on one-to-one mentorship. You get a named Accenture mentor who guides you through the programme, plus a series of virtual learning calls hosted by Accenture leaders to sharpen professional and soft skills. This is the only programme on this list where the core deliverable is a sustained individual mentor relationship rather than an event.",
        eligibility: "Second-year undergraduates in the US or Canada. No race, ethnicity, first-generation, or major criteria stated. Open to all.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "Semester-long, so there is a fall and a spring shape to it, but Accenture publishes no application dates on the student programmes page.",
        link: "https://www.accenture.com/us-en/careers/life-at-accenture/internships-students",
        note: "A semester of one-to-one mentorship outweighs a two-day conference for most people, and far fewer students apply because it demands months rather than a weekend. Accenture publishes no deadline for it, which means the only reliable route is to set a job alert on its Workday site and to ask the Accenture campus recruiter directly when the next cohort opens.",
      },
    ],
  },
  {
    key: "accounting", name: "Accounting and Big Four pipelines",
    blurb: "Pre-internship internships, leadership conferences and early-application routes at Deloitte, EY, PwC and KPMG that gate the junior-year internship and the full-time offer behind it.",
    items: [
      {
        name: "Discovery Internship", provider: "Deloitte",
        targetYear: "Freshman and Sophomore. Deloitte's own requisition titles read \"Discovery Intern (Sophomore)\" and \"Discovery Intern (Sophomore/Junior)\" depending on business.",
        whatYouGet: "A paid seven-week summer internship placed on one or more real client projects, with an assigned mentorship team: a counselor at manager or senior manager level for career guidance, plus an onboarding advisor as a peer buddy. Ongoing lunch and learns, service line spotlights, and scheduled training. Deloitte's job postings state that depending on performance, Discovery interns may be offered a subsequent internship, which is the junior-year internship that converts to full-time.",
        eligibility: "Stated in the job requisitions rather than on a marketing page: an anticipated graduation date two years out with definitive plans to pursue a bachelor's degree in accounting, business, economics, STEM or a related field. 3.0 cumulative GPA minimum, 3.2 or higher preferred. Deloitte states the internship is open to all eligible students and encourages candidates from a wide range of backgrounds. It is not identity-restricted.",
        citizenship: "No DACA language found. The requisitions carry standard Deloitte work-authorisation terms rather than a programme-specific statement.",
        openToBusiness: "",
        cycle: "No Discovery Intern requisition is open as of September 15, 2026. A search of apply.deloitte.com returns zero Discovery internship postings. The Summer 2027 cycle closed on May 1, 2026 and the requisitions now 404. Deloitte recruits Discovery on a rolling basis, so the Summer 2028 postings will appear and fill before the stated deadline.",
        link: "https://www.deloitte.com/us/en/careers/internships.html",
        note: "Deloitte has no marketing page for Discovery. The tile on its own student site points at the generic internships page, and every real detail lives only inside the job requisitions, which expire and 404 each cycle. That means the programme is effectively invisible between cycles, and the students who get in are the ones with a job alert set on apply.deloitte.com rather than the ones checking deloitte.com. Rolling admissions also means applying in month one beats applying in month five with a better resume.",
      },
      {
        name: "Deloitte National Leadership Conference (DNLC)", provider: "Deloitte",
        targetYear: "Sophomore and Junior. Page states plainly: \"Deloitte National Leadership Conference (DNLC) is open to sophomores and juniors.\"",
        whatYouGet: "A multi-day conference at Deloitte University in Westlake, Texas, with leadership development workshops, hands-on skill-building sessions, and networking with Deloitte professionals and students from across the country. The page does not state a stipend or a guaranteed interview, but the testimonials on Deloitte's own page describe DNLC leading directly to office contacts and client placements.",
        eligibility: "Page lists qualities, not criteria: naturally curious, tech savvy, excellent communicators, strong team players, continuous learning mindset. It states that specific qualifications vary by business. No race, ethnicity, or first-generation criteria appear. Open to all.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the page.",
        openToBusiness: "",
        cycle: "The page is stale. It still says \"Dates for the 2025 DNLC vary by business and office location\" as of September 2026. Dates vary by business and office, so there is no single cycle.",
        link: "https://www.deloitte.com/us/en/careers/join-deloitte/deloitte-national-leadership-conference.html",
        note: "There is no online application. Deloitte's page says outright: contact your campus recruiter to apply. That makes DNLC the one programme on this list where an ALPFA chapter relationship is the whole mechanism, because selection runs through the recruiter assigned to your school rather than through a portal. Get the ASU Deloitte campus recruiter's name and email before anything else.",
      },
      {
        name: "EY Career Residency", provider: "EY (Ernst & Young LLP, US)",
        targetYear: "Junior or Senior. The posting requires a predicted undergraduate or graduate accounting degree and the ability to meet state CPA educational requirements before starting full-time, which puts you near the end of your degree. This is not a sophomore programme.",
        whatYouGet: "A paid, two-phase programme that replaces the traditional eight-week internship. Phase one is a three-month full-time Client Service Immersion, January to March 2028, at 40-plus hours per week, primarily in person. Phase two is a five-month virtual Skills Academy, April to August 2028, at roughly 15 to 20 hours per month, and you only continue into it if you receive and accept a full-time Analyst offer at the end of phase one. The posted pay is $37.50 to $48.08 per hour. Completing it makes you eligible for a full-time Analyst role, which is a higher entry title than the traditional path.",
        eligibility: "Predicted undergraduate or graduate accounting degree with a strong academic record. Minimum 3.0 cumulative GPA, 3.2 or higher preferred. Must meet minimum CPA educational requirements for the state of your base office before full-time employment, with a demonstrable plan to pass the CPA exam. Must live within commuting distance of the assigned EY office during phase one. No race, ethnicity, or first-generation criteria. Open to all.",
        citizenship: "Restrictive and stated explicitly: \"Legal authorization to work in the US without the need for employer sponsorship, currently and in the future.\" No DACA language. Read literally, this excludes anyone who will ever need sponsorship.",
        openToBusiness: "",
        cycle: "Opening now. EY's August 17, 2026 press release states it will begin accepting applications for the inaugural class of EY Career Residents this fall, ahead of a January 2028 launch. Individual requisitions are already live on EY's early careers board.",
        link: "https://www.ey.com/en_us/assurance/ai-and-people-rising-together",
        note: "This is a structural change, not a new perk. EY is replacing the summer internship with a January to March in-person block, which means it collides with spring semester rather than summer. Nobody has run this cycle yet, so there is no upperclassman who can tell you how the academic conflict gets handled. Ask the recruiter how residents stay enrolled during a 40-hour-per-week January to March commitment before you commit to it.",
      },
      {
        name: "Destination CPA", provider: "PwC",
        targetYear: "Sophomore. Page states: sophomore year of a four-year degree program, or junior year of a five-year degree program.",
        whatYouGet: "A three-day in-person experience with future CPAs from across the country and PwC professionals, covering career paths and what a CPA license opens up. PwC pays travel and accommodation in full. You must be able to attend the entire event.",
        eligibility: "You must be an accounting major pursuing the academic requirements for CPA licensure, and you must apply to and receive a 2028 Audit or Tax Client Service internship offer from PwC. No race, ethnicity, or first-generation criteria. Open to all who meet the academic and offer criteria.",
        citizenship: "Restrictive and stated explicitly. PwC states it is not hiring entry-level job seekers who will need PwC sponsorship through the H-1B lottery now or in the future, and names the Chinese, Japanese, and Korean Business Networks as the only roles eligible for sponsorship and for participation in Destination CPA. No DACA language.",
        openToBusiness: "",
        cycle: "Applications are rolling for the 2028 internship that gates the invitation, so effectively open now. The page states \"2027 dates will be announced soon\" for the event itself.",
        link: "https://jobs-us.pwc.com/us/en/destination-cpa",
        note: "Read the order of operations carefully, because it is backwards from every other programme here. Destination CPA is not something you apply to. You apply to the 2028 Audit or Tax internship, you receive and accept that offer, and the invitation follows. So the real deadline is the internship deadline, not a conference deadline. There is also a required online assessment that arrives by email within hours of applying, and your application is not complete until you finish it, which catches people out on rolling deadlines.",
      },
      {
        name: "Embark Scholars Program", provider: "KPMG",
        targetYear: "Sophomore, effectively. The rule is stated as a remaining-semesters test rather than a class year: on completing Embark you must have at least three more semesters, or the quarter-system equivalent, before your degree and CPA eligibility requirements are done.",
        whatYouGet: "A multi-year paid internship, not a conference. Rotations through KPMG Audit, Tax, and Advisory so you can work out which practice you want, technical and professional development training, a cross-functional network of KPMG professionals, and a team Capstone project. The stated purpose is to identify the practice you want to intern in the following summer, so it feeds directly into the standard internship.",
        eligibility: "Page states: applicants must be first-generation or Community College students pursuing or intending to pursue a Bachelor or Master of accounting or equivalent, or an IT-related degree, from an accredited college or university, and be interested in a career at a public accounting firm. 3.0 GPA or above preferred. KPMG states it \"is an equal opportunity employer and encourages all qualified students with interest in the program to apply.\" This is a first-generation and community-college criterion, not a race criterion.",
        citizenship: "No citizenship, DACA, or work-authorisation language on the programme page.",
        openToBusiness: "",
        cycle: "No dates on the programme page. KPMG points you to its campus job board to find open Embark Scholar Intern requisitions, which are posted per office and per start year. Requisitions we checked from prior cycles have already expired.",
        link: "https://www.kpmguscareers.com/early-career/program/",
        note: "This is the highest-value item on the list for a first-generation ALPFA member, and it is the only one that is a paid multi-year internship rather than a conference. The community-college route is worth reading twice: a transfer student who started at Maricopa and moved to ASU qualifies on the community-college criterion even if they are not first-generation. The full brochure with the eligibility bullets is on a separate Ceros microsite that KPMG's own navigation buries.",
      },
      {
        name: "KPMG Rise Leadership Conference", provider: "KPMG",
        targetYear: "Not stated. KPMG does not publish a class year for Rise. It sits under the pre-internship section of the early-career page, which KPMG introduces with \"as early as your freshman year\", so treat it as Freshman through Junior and confirm with a recruiter.",
        whatYouGet: "A multi-day leadership programme at KPMG Lakehouse, KPMG's training campus in Lake Nona, Florida. KPMG's description states it provides scholarship opportunities, career development, and leader insights, and brings students from across the country together to build networks.",
        eligibility: "KPMG's page describes Rise as an \"inclusive leadership program\" but publishes no eligibility criteria at all. Nothing on the current page restricts it by race, ethnicity, or background.",
        citizenship: "No citizenship, DACA, or work-authorisation language published.",
        openToBusiness: "",
        cycle: "Stale. The Rise interest form still reads \"Thank you for your interest in the 2025 Rise Leadership Conference. The application is now closed\" as of September 2026. There is no published 2026 or 2027 cycle. The form collects your details to notify you of future opportunities.",
        link: "https://kpmgcampus.avature.net/rise2023app?tags=risekpmgcareerssite",
        note: "The interest form URL still carries \"rise2023\" in it and the copy still says 2025, which means nobody at KPMG has touched this page in over a year. Do not read that as the programme being dead, because it is still described on KPMG's live early-career page, but do not wait on the form either. Submit it and separately ask a KPMG campus recruiter whether Rise is running this year.",
      },
      {
        name: "KPMG Advisory Talent Program", provider: "KPMG",
        targetYear: "Not stated on the page. The application form asks for both undergraduate and graduate graduation dates, so it spans both. Confirm with a recruiter before assuming sophomore eligibility.",
        whatYouGet: "KPMG describes it as a leadership programme to attract and empower top talent, with networking, learning from industry leaders, and exploring Advisory positions at KPMG. No stipend, interview, or offer is stated.",
        eligibility: "The page tells you to review the programme qualifications before applying but does not publish them on the form. No race, ethnicity, or first-generation criteria appear anywhere on the live pages.",
        citizenship: "No citizenship, DACA, or work-authorisation language published.",
        openToBusiness: "",
        cycle: "Closed, past cycle. The form states the 2026 Advisory Talent Program application closed on March 9, 2026, and offers a notification signup for the 2027 programme. Expect a January or February window.",
        link: "https://kpmgcampus.avature.net/advisorytalentprogram?source=Avature+Portal&tags=atpkpmgcareersite",
        note: "This is the Advisory-side equivalent of what most students only know on the Audit and Tax side, and it matters because Advisory is where the consulting-style work sits at KPMG. The notification form is worth filling in now: it is the only way to be told when the 2027 window opens, since KPMG does not announce it on the main careers page.",
      },
      {
        name: "Early Internship Application and Global Advantage Program", provider: "KPMG",
        targetYear: "Sophomore. KPMG's wording is \"two years prior to graduation\", which for a four-year degree means applying in your sophomore year for an internship that sits between sophomore and junior year.",
        whatYouGet: "An expedited route: KPMG accepts internship applications two years before graduation rather than one. Once you receive an internship offer, a selected subset is invited to Global Advantage, a four-day international programme. Previous hosts were Prague, Brussels, and Copenhagen. The page states that after you submit your application for a 2027 internship position, eligible candidates are automatically emailed the link to apply to Global Advantage.",
        eligibility: "Open to any student applying for a KPMG internship two years before graduation. Global Advantage selection is a subset of internship offer-holders. No race, ethnicity, or first-generation criteria stated.",
        citizenship: "No citizenship or DACA language on the page. Global Advantage involves international travel, so a passport and the ability to travel are implied but not stated.",
        openToBusiness: "",
        cycle: "Rolling. The page currently references applications for 2027 internship positions.",
        link: "https://www.kpmguscareers.com/early-career/program/",
        note: "This is the single most underused mechanism in the Big Four. Most sophomores assume internship applications are a junior-year thing, so the sophomore applicant pool is small, and KPMG explicitly invites it. The Global Advantage invitation is automatic once you hold an offer, which means the whole thing is gated by applying a year earlier than your classmates and nothing else.",
      },
    ],
  },
  {
    key: "employer", name: "Employer run tech programmes",
    blurb: "Programmes run directly by Microsoft, Amazon, Google and Salesforce, which pay well and carry a return offer but now gate hard on year of study, technical coursework and in most cases a CS major.",
    items: [
      {
        name: "Explore Microsoft Program", provider: "Microsoft",
        targetYear: "Freshman and Sophomore. There are two separate applications, one for first-year and one for second-year undergraduates, and the page tells you not to apply to both.",
        whatYouGet: "A 12-week paid US summer internship (8 weeks in India). You work in a pod with other Explore interns rather than alone on a team, and you rotate through both Program Manager and Software Engineer work across the design, build and quality phases. You get a mentor, community programming and networking. It is the recognised on-ramp to a standard Microsoft university internship later.",
        eligibility: "First or second year of a bachelor's degree in the United States, Canada or Mexico (the second-year application also covers India). Non-CS and business majors CAN apply: the FAQ says plainly 'We do not require you be a computer science major to apply.' The hard gate is coursework, not major: you must have completed an Introduction to Computer Science course or equivalent AND one semester of calculus or equivalent. A business major who has taken an intro programming course and a calc course qualifies; one who has not, does not.",
        citizenship: "The page sets no citizenship or residency rule. It scopes by country of study only. It says nothing about visa sponsorship, so do not assume either way.",
        openToBusiness: "Business majors yes, with intro CS plus one calculus course",
        cycle: "Summer programme, mostly at Redmond WA, Atlanta GA and India campuses. The page does not publish an application window. As of 2026-09-15 no Explore-specific posting was visible.",
        link: "https://careers.microsoft.com/v2/global/en/exploremicrosoft",
        note: "The 'Explore Program internships' job list at the bottom of that page is not filtered to Explore. On 2026-09-15 it was showing a National Technology Intern role in Paris, a Government Affairs Intern role and a Senior Software Engineer role. Do not read that widget as the Explore posting list, and do not conclude from it that applications are open or closed.",
      },
      {
        name: "Microsoft Discovery Program", provider: "Microsoft",
        targetYear: "High school senior, entering as a rising first-year. Current college students are not eligible.",
        whatYouGet: "A 4-week paid onsite internship with a real project, mentorship from Microsoft employees, and professional skills work.",
        eligibility: "Graduating high school seniors who live and attend high school within 50 miles of Redmond, Washington, or who attend school in the Atlanta Public Schools, DeKalb, Fulton, Cobb or Gwinnett county districts. You must have completed pre-calculus or equivalent by the start of the programme. For Redmond, applicants must be members or participants of Microsoft-sponsored organisations. Major is irrelevant because you have not declared one yet, but nobody currently enrolled at ASU can use this.",
        citizenship: "Not stated on the page.",
        openToBusiness: "Not applicable, pre-college",
        cycle: "Applications open in early February, reviewed on a rolling basis, interviews scheduled from March, 4 consecutive weeks between July and August. The page still displays the 2026 dates (Atlanta 6 July to 31 July 2026, Redmond 13 July to 7 August 2026), which is a past cycle as of 2026-09-15.",
        link: "https://careers.microsoft.com/v2/global/en/discoveryprogram",
        note: "This is gated on geography, not on academic merit. Microsoft's own students hub describes it loosely as open to 'rising first-year college students', which reads as available to anyone. The programme page itself is far narrower. Tell chapter members with younger siblings in Atlanta or Seattle, not members here.",
      },
      {
        name: "Microsoft Leap", provider: "Microsoft",
        targetYear: "Any, but it is aimed at people past a degree rather than current undergraduates. The page frames it around career changers, people re-entering the workforce and self-taught or bootcamp backgrounds.",
        whatYouGet: "A 16-week immersive apprenticeship combining classroom learning with hands-on engineering on real Microsoft product teams such as Azure, Xbox, Bing and Office 365.",
        eligibility: "The page asks for 'a base foundation of technical training' and 'broad professional experience'. It does not require a CS degree, and it explicitly targets non-traditional academic paths, so a business graduate who has done technical training is in scope. It is not a student programme.",
        citizenship: "Not stated on the landing page.",
        openToBusiness: "Business backgrounds yes, but not for current students",
        cycle: "Not stated. The landing page publishes no cohort dates and no application window, and applications run through individual cohort postings on Microsoft Careers.",
        link: "https://leap.microsoft.com/en-US/",
        note: "The page served to a script carries the string 'You're offline. This is a read only version of the page', which is how the site degrades. Treat the content as accurate but the page as lightly maintained, and go to Microsoft Careers for live cohort postings rather than waiting for this page to change.",
      },
      {
        name: "Amazon Future Engineer Scholarship and Internship", provider: "Amazon",
        targetYear: "High school senior. You apply before you start college. Current undergraduates cannot enter.",
        whatYouGet: "Up to $10,000 a year for up to four years, maximum $40,000, plus a paid Amazon software engineering internship. Interns sit embedded on a software team with a manager, tech mentors and a dedicated career mentor, and most ship production code. Winners in the testimonials interned at Amazon after their freshman year.",
        eligibility: "US high school senior currently enrolled in or having completed a computer science course (or you can opt into an Amazon assessment instead), minimum 2.3 GPA on a 4.0 scale, demonstrated financial need, and planning a bachelor's in a listed technical major. Business majors are NOT eligible. The accepted list is Computer Science, Computer Engineering, Software Engineering, Computer Programming, Math, Data Science, Electrical Engineering, Transportation Technology, Computer Info Systems, Computer Info Science, Cognitive Science, Informatics and Information Technologies.",
        citizenship: "'Must be authorized to work in the U.S. Example: Employment Authorization Document holder, Permanent Resident, or U.S. Citizen.' An EAD holder qualifies, which covers DACA recipients with valid work authorisation. No visa sponsorship.",
        openToBusiness: "No, CS and adjacent technical majors only",
        cycle: "The page states 'Applications for 2025-2026 are closed' as of 2026-09-15, so it is displaying a past cycle. There is a newsletter signup for the next opening and no announced date.",
        link: "https://www.amazonfutureengineer.com/scholarships",
        note: "The money is not the point, the internship is. Amazon's own university site says 'Our internships are for rising seniors and recent graduates', so this scholarship is currently the only documented route into an Amazon software internship as a freshman. If you are already at ASU, that door is shut and there is no equivalent.",
      },
      {
        name: "Futureforce Tech Launchpad", provider: "Salesforce, delivered by CodePath",
        targetYear: "Sophomore, entering as a rising junior. The page says 'students who will complete their sophomore year in Spring 2026' and lists bachelor's graduation year 2028.",
        whatYouGet: "A paid 10-week full-time summer pre-internship. You are hired by Salesforce, work 9 to 5 onsite at Salesforce Tower in San Francisco, get a relocation stipend, a professional Salesforce mentor, CodePath instructors and TAs, and you finish with a deployed full-stack app built with React, Node, Express, PostgreSQL and AI tooling. The stated purpose is to make you competitive for a senior-year internship.",
        eligibility: "Age 18+, major in Computer Science or Computer Engineering at a US college or university, and completed a CS1-type intro programming course with proficiency in functions, conditionals, loops, variables, primitive types and arrays. Business majors are NOT eligible as the page is written.",
        citizenship: "Not stated on the page.",
        openToBusiness: "No, CS or Computer Engineering only",
        cycle: "The page still shows the 2026 cycle: info session 22 January 2026, application deadline 22 February 2026, programme 1 June to 7 August 2026. That cycle is over as of 2026-09-15 and the page now offers a waitlist.",
        link: "https://info.codepath.org/futureforce-tech-launchpad",
        note: "Stage two is an HTML and CSS project plus a 10-minute recorded video answering interview prompts. That screens for follow-through rather than resume prestige, which is unusually favourable if your resume is thin. Join the waitlist now so you catch the January info session rather than discovering it in February.",
      },
      {
        name: "Google Associate Product Manager (APM) Program", provider: "Google",
        targetYear: "Junior and Senior for the internship, Senior and recent graduate for the full-time role. The internship accepts 'students who will graduate from their degree program within 12 months of completing their internship'.",
        whatYouGet: "For full-time APMs: two one-year rotations on different products, then you choose whether to stay or move. One-to-one professional development with a management coach, an APM Alumni Advisor who was once an APM, a buddy from the class above, an international trip where your whole class visits cities to meet local tech leaders, and US mini-trips on topics you choose. Class size is roughly 45 a year with an alumni network of 600+. The APM internship is 12 weeks over the summer on one team, and the page says many APM interns return as full-time APMs.",
        eligibility: "No stated major requirement. Google asks for entrepreneurial people with 'strong technical understanding, product sense, analytical ability, and clear communication skills'. The honest caveat is in Google's own words: for full-time roles, 'Candidates typically have a technical background in computer science or a related area'. A business major can apply and should, but should expect to be assessed on technical fluency.",
        citizenship: "Not stated on the programme page. Locations are the San Francisco Bay Area, New York, London, Munich, Zurich and Tokyo.",
        openToBusiness: "Business majors can apply, but Google says APMs typically have a technical background",
        cycle: "The page states US-based Internship and University Graduate APM applications are open from September 22nd to October 6th, and the London-based Internship window is October 5th to November 12th. No year is printed, but the page is live on 2026-09-15, so the US window opens in one week. Google adds 'You must apply during open application windows to be considered' and recommends applying promptly. There is no information yet on APM University Graduate windows for London or Bengaluru.",
        link: "https://www.google.com/about/careers/applications/programs/apm/",
        note: "This is the one live, dated, business-relevant Google deadline anyone in your chapter can act on right now, and it is the only Google student programme left with a real landing page. Set the job alert today rather than checking the page, because the window is two weeks long and Google does not post a reminder.",
      },
      {
        name: "US Google Student Ambassador Program", provider: "Google",
        targetYear: "Any undergraduate. The page does not state a year requirement.",
        whatYouGet: "A virtual campus ambassador role that runs on the academic calendar. Google lists it as one of only three developmental programmes it currently offers.",
        eligibility: "Not stated on the programmes listing. There is no published major requirement, which makes it the most plausible Google entry point for a business major who is not applying to APM.",
        citizenship: "Not stated. The programme is US-scoped by its name.",
        openToBusiness: "No major restriction published",
        cycle: "'Based on academic calendar'. No application window is published on the listing.",
        link: "https://www.google.com/about/careers/applications/buildyourfuture/programs/googlestudentambassador",
        note: "The description on Google's own programmes listing for this card is a copy-paste error: it repeats the Google Summer of Code text word for word. So the card tells you nothing about the ambassador programme. Go to the programme page itself, and do not quote the listing blurb to your members.",
      },
      {
        name: "Google Summer of Code", provider: "Google",
        targetYear: "Any. Google does not scope it by year of study on the current pages.",
        whatYouGet: "A 12+ week paid online programming project with an open source organisation, under the guidance of mentors from that community. Google's framing is 'bringing new contributors into open source software development', so it is aimed at newcomers rather than experienced contributors. Over 1,000 organisations have mentored 21,000+ contributors since 2005.",
        eligibility: "The current public pages describe it as open to people new to open source. The detailed eligibility and stipend rules sit behind a JavaScript-rendered rules page that would not return text to a scripted request, so I am not going to state a GPA, age or residency rule I could not read. Assume you need to be able to code before you apply, which rules out most business majors without a programming background.",
        citizenship: "Not verified. The rules page did not render to a script. Google Summer of Code has country restrictions tied to US sanctions law, so check the rules page in a browser before you commit.",
        openToBusiness: "No major bar, but you need working programming ability",
        cycle: "Annual, 12+ weeks. As of 2026-09-15 the site shows 'Organization registration closed', which is the step before contributor applications open.",
        link: "https://summerofcode.withgoogle.com/",
        note: "The selection is not really an application, it is a relationship. Google's own advice is that reaching out to organisations early and having conversations before you submit a proposal is what gets you selected. Somebody who starts talking to a mentoring org in the autumn beats somebody with a better resume who submits cold in the spring.",
      },
    ],
  },
  {
    key: "nonprofit", name: "Nonprofit run, free, and open to more majors",
    blurb: "The tier that now carries the freshman and sophomore load, mostly free, mostly open to any major, and in several cases the route through which employer programmes actually recruit.",
    items: [
      {
        name: "CodePath courses (Technical Interview Prep, Applied AI Engineering, Web Development, Cybersecurity)", provider: "CodePath (501(c)(3) nonprofit)",
        targetYear: "Any undergraduate.",
        whatYouGet: "Free 10-week virtual instructor-led courses taught by senior engineers, 4 to 10 hours a week, meeting once or twice weekly. Technical Interview Prep gives you data structures and algorithms, the UMPIRE problem-solving method, and mock interviews for internship and full-time roles. The AI pathway includes free access to Claude and Claude Code. Alongside the courses you get the Career Kit, Career Labs, a Career Bot, resume and application support, workshops, and Tech Fellowship leadership roles on your campus.",
        eligibility: "The course pages market the courses as 'at no cost to CS students', but the About page states 'Our courses are open to students of all backgrounds' and the site reports 50,000+ college students enrolled from 1,000+ colleges. There is no published major bar. Business majors can apply and should start at the intro level of a pathway, because the intermediate and advanced courses assume working programming ability.",
        citizenship: "Not stated.",
        openToBusiness: "Business majors yes, start at the intro course",
        cycle: "Runs by academic term with rolling enrolment. As of 2026-09-15 spring enrolment is open with a waitlist and countdown on each pathway.",
        link: "https://www.codepath.org/courses",
        note: "CodePath is the recruiting and training machinery behind other companies' pre-internships, including Salesforce Futureforce Tech Launchpad and Claude Corps, where it is the employer of record. Taking a CodePath course is how you become visible to those pipelines, which is worth more than the course content on its own.",
      },
      {
        name: "Claude Corps", provider: "Anthropic with CodePath and Social Finance",
        targetYear: "Senior and recent graduate. Anyone with two years or fewer of full-time work experience.",
        whatYouGet: "A 12-month fully paid fellowship. You are a full-time W-2 CodePath employee with salary and benefits for the whole year. CodePath designs the AI-native curriculum and trains you throughout, and you are placed with a nonprofit host organisation to build AI tools and systems for them.",
        eligibility: "The FAQ states there is no minimum education requirement and no technical background required. Business majors and non-CS majors are explicitly fine. You do not need to be a CodePath student. This is the only programme in this list with no technical prerequisite at all.",
        citizenship: "You must be authorized to work in the United States.",
        openToBusiness: "Business majors yes, no technical background needed",
        cycle: "Cohort 1 applications are open now and recruitment is rolling, so apply as soon as you are ready. The programme was announced 11 June 2026.",
        link: "https://www.anthropic.com/claude-corps",
        note: "The host organisations for Cohort 1 must be Anthropic nonprofit Enterprise or Team customers with a hybrid or in-person workplace, and fully remote hosts do not get fellows until 2027 cohorts. That means placements cluster where those nonprofits are. Ask about location before you build a plan around it.",
      },
      {
        name: "Break Through Tech AI Program", provider: "Break Through Tech",
        targetYear: "Any undergraduate. The programme is designed to sit before your final year so the portfolio is ready when you apply for internships.",
        whatYouGet: "A free virtual extracurricular. Machine Learning Foundations curriculum working with industry tools on real data sets, ending in a machine learning certificate from Cornell University. Then AI Studio, where you tackle real ML Challenge Projects with academic and industry advisors to build a portfolio. Plus an industry mentor working with you in a small group of fellows, with case studies, skill-building simulations and personalised feedback.",
        eligibility: "Undergraduates at a US-based college or university pursuing tech-related fields. The FAQ says 'Yes, we accept applications from all majors', with the caveat that computing, IT and engineering majors 'will be best prepared for the rigors of the program'. No prior internship experience needed. Business majors can apply.",
        citizenship: "Not stated.",
        openToBusiness: "Business majors yes, all majors accepted",
        cycle: "'Application timelines vary by program and cohort.' No dates are published. You submit an interest form and they notify you when applications open.",
        link: "https://www.breakthroughtech.org/programs/",
        note: "Break Through Tech no longer states any gender eligibility anywhere on its current programme, FAQ or homepage. If somebody tells your chapter it is women-only, that is out of date as of 2026-09-15. The Cornell certificate is the part that survives a resume screen at a firm that does not know Break Through Tech.",
      },
      {
        name: "Break Through Tech Sprinternship", provider: "Break Through Tech",
        targetYear: "Freshman and Sophomore. The page says 'early undergraduate students'.",
        whatYouGet: "A full-time paid micro-internship during an academic break. You work in a cohort on a real technical challenge at a host company, guided by industry professionals, onsite, hybrid or remote. You leave with a resume project, a company network and experience of a professional environment before your first real internship.",
        eligibility: "Same Break Through Tech eligibility: undergraduate at a US-based college pursuing tech-related fields, all majors accepted, no prior internship experience required. Business majors can apply.",
        citizenship: "Not stated.",
        openToBusiness: "Business majors yes, all majors accepted",
        cycle: "Runs during academic breaks. No published dates. You inquire to join.",
        link: "https://www.breakthroughtech.org/programs/",
        note: "With Meta University gone and Amazon restricted to rising seniors, this is now the closest thing left to a real company project before junior year that a non-CS major can actually get into. Host placement depends on which companies are running Sprinternships in your region, so ask that question in the interest form rather than assuming Phoenix coverage.",
      },
      {
        name: "Break Through Tech Agentic AI", provider: "Break Through Tech",
        targetYear: "Any undergraduate. Described as beginner.",
        whatYouGet: "A 16-week hands-on programme. You learn what separates an AI agent from a chatbot, build one with LangChain and LangGraph, evaluate and debug it with observability tools, then package and deploy it to a public URL. You work in a team and finish with a publicly accessible portfolio project you can defend in an interview. Coaches and peers support you throughout. Free.",
        eligibility: "Same Break Through Tech eligibility: US-based undergraduate, all majors accepted. Business majors can apply, and this is the most approachable of the three for somebody with no programming background.",
        citizenship: "Not stated.",
        openToBusiness: "Business majors yes, all majors accepted",
        cycle: "16 weeks. Timelines vary by cohort and are not published. Interest form only.",
        link: "https://www.breakthroughtech.org/programs/",
        note: "The stated outcome is not the code, it is being able to 'explain and defend your technical work'. For a business major that is the actual asset: a deployed thing with a URL you can talk about for ten minutes. Fellows are allowed to do more than one Break Through Tech programme, so this stacks with the AI Program.",
      },
      {
        name: "ColorStack membership", provider: "ColorStack (501(c)(3) nonprofit)",
        targetYear: "Any undergraduate.",
        whatYouGet: "Membership in a community of 14,000+ students from 1,000+ schools. An active Slack workspace, monthly Fam Fridays sessions with keynote speakers and engineers, a career fair twice a year, and mentorship, workshops and recruiting access through 40+ partner tech companies. Members report that being affiliated with ColorStack itself gave them an edge with interviewers.",
        eligibility: "Two hard gates. First, you must be enrolled in a US or Canadian undergraduate Computer Science or closely related major, with Data Science, Computer Engineering and Information Systems named as acceptable. Second, you must identify as an undergraduate Black, Latinx, Native American or demonstrated ally. Business majors are explicitly REJECTED: the FAQ names Business alongside Civil Engineering and Psychology as majors they do not accept and do not provide resources for. Your application details must match your LinkedIn exactly, including school, major and graduation year, or you are denied.",
        citizenship: "No citizenship rule, but you must be studying in the US or Canada. The FAQ says students studying in any other country are not eligible.",
        openToBusiness: "No for general business, yes for Information Systems",
        cycle: "Applications reviewed on a rolling basis, year-round. Free.",
        link: "https://www.colorstack.org/member-application-requirements",
        note: "Information Systems is on the accepted list, so an ASU Computer Information Systems student in W. P. Carey can get in where a Finance or Marketing major cannot. That single distinction is worth telling your members before they waste an application. Fix your LinkedIn to match before you apply, because a mismatch is the most common rejection reason on their own FAQ.",
      },
      {
        name: "Rewriting the Code membership", provider: "Rewriting the Code (501(c)(3) nonprofit)",
        targetYear: "Any. Explicitly university through the first six years of a tech career. If you have more than six years of experience they route you to join as a mentor instead.",
        whatYouGet: "Free membership. A 24/7 Slack community, near-peer mentors who recently went through what you are facing, small-group Mentor Circles, technical interview prep with peers who recently passed those interviews, resume reviews from industry professionals, the Virtual Career Summit with 25+ companies actively hiring, the TechConnect spring recruiting fair in January, in-person Tech Hub meetups, nSpire AI as a 24/7 career coach, and limited perks such as conference support and access to tools like LeetCode or LinkedIn Premium.",
        eligibility: "Women in tech. There is no stated major restriction anywhere on the current site, and the RISE programme is described as supporting 'university women from their first year through their first role'. Business majors who intend to work in tech can apply. Applications are manually reviewed and take up to 48 hours.",
        citizenship: "Not stated. It is a global community with Tech Hubs in San Francisco, Seattle, Boston, New York City, Toronto and London.",
        openToBusiness: "Business majors yes, no major restriction stated",
        cycle: "Rolling, free, takes about five minutes to apply. Career Summit in August (US), UK and Ireland Career Summit in October, TechConnect recruiting fair in January.",
        link: "https://rewritingthecode.org/join-us/",
        note: "RTC runs affinity groups including Latinas de RTC, so there is a Latina sub-community inside the larger one. Also note the Future of Tech Fund, their financial assistance arm, currently says 'Applications are currently paused', so do not point members at it as a funding route right now.",
      },
      {
        name: "Latinas in Tech, LiT 365 membership and Vibe Coding AI Agents", provider: "Latinas in Tech (501(c)(3) nonprofit)",
        targetYear: "Any. This is a professional community, not a student pipeline.",
        whatYouGet: "LiT 365 Silver is free and gives you the community, networking, resources and chapter events, plus the LiT Recruit job platform. Gold is $100 a year and adds exclusive events, discounts and more access to industry leaders. Platinum is $300 a year and is aimed at senior leaders. The only programme currently listed is Vibe Coding AI Agents, a 4-week live beginner-friendly course led by instructor Alex Garcia on how AI agents work and how to build one.",
        eligibility: "LiT 365 Silver is described as 'open to everyone, whether you're taking your first step or paving the way for others'. No major requirement, no degree requirement. Business majors can join freely.",
        citizenship: "Not stated.",
        openToBusiness: "Business majors yes, open to everyone",
        cycle: "Membership is rolling. Vibe Coding AI Agents shows a Register Now link as of 2026-09-15 with no stated deadline on the programmes page.",
        link: "https://latinasintech.org/programs",
        note: "As of 2026-09-15 the Programs page lists exactly one programme. Treat Latinas in Tech as a chapter, mentorship and networking play, not as a structured pipeline with cohorts and placements. Also, www.latinasintech.org would not resolve for a scripted request while the apex latinasintech.org did, so use the apex domain in any link you publish.",
      },
      {
        name: "SHPE Undergraduate membership and MentorSHPE", provider: "Society of Hispanic Professional Engineers",
        targetYear: "Any undergraduate.",
        whatYouGet: "For $10 a year: exclusive access to the SHPE Career Center, where corporate partners search member resumes for internships and post roles year-round. Plus resume reviews and rewording, professional development, leadership training, mentoring from a professional member, internship, fellowship and co-op opportunities, discounted registration for national and regional events, and eligibility to hold office. MentorSHPE adds a three-month one-to-one mentoring connection that you initiate and structure around two to five goals, or single-session Mentoring Moments if you want interview or grad school advice without the commitment.",
        eligibility: "'Undergraduate membership is open to all college students studying science, technology, engineering, or mathematics.' Business majors are not covered by that wording. Management Information Systems or Computer Information Systems is the closest fit and SHPE's own InternSHPE materials list information systems, supply chain, finance and accounting tracks, so it is worth asking rather than assuming. You do NOT have to be Hispanic to join.",
        citizenship: "Not stated.",
        openToBusiness: "STEM majors only as written, ask if you are MIS or CIS",
        cycle: "Rolling, $10 a year for undergraduates, $15 for graduate students including MBA candidates. Hardship vouchers are available for members who cannot afford dues.",
        link: "https://shpe.org/membership/become-a-member/",
        note: "The MentorSHPE matching platform is mid-migration to new software as of 2026-09-15 and the page says to stay tuned for the launch, so the mentoring queue is effectively stalled right now. SHPE's real yield for a student is the National Convention career fair and the Career Center resume book, not the website. Note also that www.shpe.org/students/ returns 404, the programmes live under shpe.org/engage/programs/.",
      },
      {
        name: "Techqueria membership", provider: "Techqueria (501(c)(3) nonprofit)",
        targetYear: "Any, including Student as a listed role category.",
        whatYouGet: "Free membership in a 25,000-strong network with 19,000+ Slack members and around 3,000 weekly active members. You get the Slack community, free events and workshops, a bi-monthly newsletter, the job board, mentorship, and the option to have your profile shared with recruiters in their network. Local chapters and an annual summit.",
        eligibility: "Open application, manually reviewed. You must be 18 or over. The form asks whether you identify as Latinx or as an ally, and states plainly 'You will get an invite either way'. You must be currently in tech or interested in entering tech. The job category list includes Accounting, Finance, Marketing, Sales, Operations, Product and Student, so business majors are squarely in scope.",
        citizenship: "No citizenship requirement. The form accepts any country.",
        openToBusiness: "Business majors yes, explicitly including finance, accounting, marketing and sales",
        cycle: "Rolling, free. Five-step application form, LinkedIn URL required, resume optional.",
        link: "https://techqueria.org/get-involved/join/",
        note: "Two things the page does not advertise. First, allies are admitted, so a non-Latino chapter member is not wasting their time. Second, there is an explicit opt-in to let Techqueria share your profile with recruiters. Say yes and upload the optional one-page PDF resume, because that consent is the only part of this membership that acts like a pipeline rather than a chat room.",
      },
    ],
  },
];

