#!/usr/bin/env python3
"""
Pull the chapter's events out of ClickUp and write events.js for the website.

Runs on GitHub's servers once a day (see .github/workflows/sync-events.yml),
so the calendar on the homepage refreshes without anybody logging in anywhere.

Where the events live: the "Events Pipeline" space in the ALPFAatASU workspace,
one list per kind. Each task is one event. Its date and time are the task's own
Start and Due dates. The venue is the "Location/Venue:" line in the description,
which every event task carries because they are all duplicated from one
template task. Cancelled tasks are left out. Nothing else is filtered: a past
event stays in the list, the calendar simply shows it in its month.

Writes events.js, which index.html loads AFTER data.js. It sets
window.EVENTS_LIVE, and the homepage uses that when present and the hand
written EVENTS in data.js when not. So the site keeps working with no token,
no network and no Action, it just shows the hand written list.

Needs CLICKUP_TOKEN in the environment. Without it the script says so and
exits 0 on purpose, so a fresh clone or an Action run before the secret is set
does not produce a red X.
"""
import json, os, sys, re, datetime, urllib.request, urllib.error

TEAM = "90132880215"
LISTS = {                      # ClickUp list id -> the "kind" the site shows
    "901327263715":     "Social",
    "901327263720":     "Professional",
    "901327263869":     "Networking",
    "1000400000010441": "Board",
    # "901327627845" is ASU Calendar Dates: university dates, not chapter events. Left out.
}
PHOENIX = datetime.timezone(datetime.timedelta(hours=-7))   # Arizona never changes clocks
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "events.js")


def fetch(list_id, token):
    tasks, page = [], 0
    while True:
        url = f"https://api.clickup.com/api/v2/list/{list_id}/task?include_closed=true&subtasks=false&page={page}"
        req = urllib.request.Request(url, headers={"Authorization": token})
        with urllib.request.urlopen(req, timeout=30) as r:
            data = json.load(r)
        tasks += data.get("tasks", [])
        if data.get("last_page", True) or not data.get("tasks"):
            break
        page += 1
    return tasks


def day(ms):
    """ClickUp dates are epoch milliseconds. Return a local Phoenix ISO day."""
    if not ms:
        return None
    return datetime.datetime.fromtimestamp(int(ms) / 1000, PHOENIX).date().isoformat()


def venue(description):
    """The template puts the venue on a labelled line. Read that line only, and
    give up rather than guess when it is not there. A wrong venue sends a
    student to the wrong building, an empty one sends them to the group chat."""
    if not description:
        return ""
    m = re.search(r"Location\s*/?\s*Venue\s*:\s*(.+)", description, re.I)
    if not m:
        return ""
    v = m.group(1).strip().splitlines()[0].strip(" -*_")
    return "" if v.lower() in ("", "tbd", "tba", "empty") else v


def to_event(task, kind):
    if (task.get("status") or {}).get("status", "").lower() == "cancelled":
        return None
    start, due = day(task.get("start_date")), day(task.get("due_date"))
    date = start or due
    if not date:
        return None                     # an event with no date cannot go on a calendar
    ev = {"date": date, "title": task["name"].strip(), "where": venue(task.get("description")), "kind": kind}
    if due and due != date:
        ev["end"] = due
    return ev


def main():
    token = os.environ.get("CLICKUP_TOKEN", "").strip()
    if not token:
        print("CLICKUP_TOKEN is not set. Nothing synced; the site keeps its hand written EVENTS.")
        return 0
    events = []
    for list_id, kind in LISTS.items():
        try:
            tasks = fetch(list_id, token)
        except urllib.error.HTTPError as e:
            print(f"ClickUp returned {e.code} for list {list_id} ({kind}). Skipping it.", file=sys.stderr)
            continue
        for t in tasks:
            ev = to_event(t, kind)
            if ev:
                events.append(ev)
    events.sort(key=lambda e: (e["date"], e["title"]))
    stamp = datetime.datetime.now(PHOENIX).strftime("%Y-%m-%d %H:%M")
    body = "/* GENERATED by tools/sync_events.py from ClickUp on " + stamp + ". Do not edit by hand,\n" \
           "   the next daily run overwrites it. Edit the event in ClickUp instead. */\n" \
           "window.EVENTS_LIVE = " + json.dumps(events, indent=2, ensure_ascii=False) + ";\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"Wrote {len(events)} event(s) to events.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
